### ISSUE TITLE
为什么搜索出来的是您博客中的文章？

### ISSUE THREAD

**Issue by BBBoundary** [androiddevelop/jekyll-search#10]
按照步骤把所有代码都贴好了，但是搜索出的文章都是您博客下的文章
不知道代码哪里需要改
博客：bbboundary.github.io

**Comment by androiddevelop** [comment]
需要修改请求的地址

**Comment by androiddevelop** [comment]
![image](https://user-images.githubusercontent.com/3939943/104847520-75c89200-591b-11eb-9f49-6228a5aedb16.png)
看到博客中一共有2个jquery

**Comment by BBBoundary** [comment]
成功了，非常感谢！
