### ISSUE TITLE
“加入步骤”第2条   cb-footer-add.html 中内容放在 </footer> 前并不可行

### ISSUE THREAD

**Issue by KICIOLLO** [androiddevelop/jekyll-search#2]
如题所说，将cb-footer-add.html 中内容放在 </footer> 前并不可行。
我通过查看您博客模板的具体文档和footer.html文件，发现上述内容不应放置在  </footer> 之前，而是放在该文件末尾即可正常使用搜索功能。
望周知，并修改说明文档，很棒的功能希望可以被更多人了解和使用。

**Comment by androiddevelop** [comment]
非常感谢您的细心观察及反馈，内容是需要放在在footer的后面，已经修正，谢谢。
