### ISSUE TITLE
blog 界面是显示搜索框了，就是没候选选项，也不能搜索到任何东西

### ISSUE THREAD

**Issue by sinsa110** [androiddevelop/jekyll-search#3]
问题如题

博客地址
https://sinsa110.github.io/

**Comment by androiddevelop** [comment]
![image](https://user-images.githubusercontent.com/3939943/38779116-7555424a-40f6-11e8-8c19-11c0202fc81c.png)

放置有问题，cb-search.js和bootstrap3-typeahead.min.js请放在jquery后面，如图所示。

**Comment by sinsa110** [comment]
@androiddevelop 问题解决了，非常感谢🙏
