### ISSUE TITLE
出现bootstrap css覆盖原css

### ISSUE THREAD

**Issue by Mabbs** [androiddevelop/jekyll-search#7]
能不能不用bootstrap css？

**Comment by Mabbs** [comment]
胡乱搞了一堆样式勉强解决了问题：

`.dropdown-menu {

    position: absolute;

    top: 100%;

    left: 0px;

    display: none;

    float: left;

    padding: 5px 0;

    margin: 2px 0 0;

    font-size: 14px;

    text-align: left;

    list-style: none;

    background-color: #fff;

    -webkit-background-clip: padding-box;

    background-clip: padding-box;

    border: 1px solid #ccc;

    border: 1px solid rgba(0,0,0,.15);

    border-radius: 4px;

    -webkit-box-shadow: 0 6px 12px rgba(0,0,0,.175);

    box-shadow: 0px 6px 12px rgba(0,0,0,0.175);

}





.dropdown-menu > .active > a, .dropdown-menu > .active > a:focus, .dropdown-menu > .active > a:hover {

    color: #fff;

    text-decoration: none;

    background-color: #337ab7;

    outline: 0;

}

.dropdown-menu > li > a {

    display: block;

    padding: 3px 20px;

    clear: both;

    font-weight: 400;

    line-height: 1.4285;

    color: #333;

    white-space: nowrap;

}

* {

    -webkit-box-sizing: border-box;

    -moz-box-sizing: border-box;

    box-sizing: border-box;

}`

**Comment by androiddevelop** [comment]
样式了用了bootstrap css, 后面我看下怎么剥离出来
